### PR TITLE
Add configuration showWelcomeText

### PR DESCRIPTION
**Pull request by ryanraposo**
Before anything just remember, its always your call. Sometimes your job is to say 'No' and if you want to back up on the feature itself, or any part of it, don't hesitate to say that to me or anyone.

Anyways! The changes:

- Add showWelcomeText configuration (package.json)
- Add the Config class and related methods (config.ts) (new)
- Update reading of configs and how they're passed to the webview. (webViewProvider.ts)
- Add logic for welcomeText (main.js)

### CODE REVIEW

**Comment by AssisrMatheus** [comment]
I tried running the extension but I got two issues:
- A prettier error of a missing `;` here: https://github.com/AssisrMatheus/sidebar-markdown-notes/blob/977ffc774f77fd9f2cdaebf285d3634508d09324/src/webviewProvider.ts#L55
- After fixing the prettier errors, the settings didn't seem to work
U1udwCOoYG.

Ps: I recommend installing the prettier + eslint extension, so it shows you errors and auto fixes available issues based on the project rules. It is not required though and you can use the cli if you prefer.

**Comment by ryanraposo** [comment]
> I tried running the extension but I got two issues:
> 
> Ps: I recommend installing the prettier + eslint extension, so it shows you errors and auto fixes available issues based on the project rules. It is not required though and you can use the cli if you prefer.

👍will look into both.

**Comment by ryanraposo** [comment]
Alright so I added the behavior, but it raised some questions about states and persistence. I guess we need to establish what the case is for a few things, like new 'notebooks'. Or consecutive blank pages; should we disallow them? We could purge states on load of blank pages?

Whatever the system, it should update its index on pages and I was thinking the display might be something like this:

pageno

**Comment by ryanraposo** [comment]
@AssisrMatheus  I think it'd be better to hold off on this feature and in the mean time think about the end-game for pages, states, and 'notebooks'. 

After getting familiar with the extension and the codebase I want to walk it back and submit a new PR with just the update to configurations and how they're initialized.

**Pull request closed without merging**
