### PR TITLE
✨Added support for checking checkboxes

### PR DESCRIPTION
**Pull request by zbarbuto**
Checkboxes were previously completely disabled. Now, when a checkbox is
checked, the corresponding markdown for that checkbox is updated to
be checked/unchecked.

Known issue is that this won't work so well if multiple checkboxes
have the same content but is a starting point

Demo:

https://user-images.githubusercontent.com/9100419/188522112-19e89ec6-ce7a-4ad0-90d4-add686e03db0.mov

### CODE REVIEW

**Comment by zbarbuto** [comment]
Ping @AssisrMatheus - only because last commit was 2 years ago+ not sure if you still monitor this repo or get notifications about PRs.

**Comment by techuila** [comment]
☝️

**Comment by AssisrMatheus** [comment]
Thank you for the ping. Really missed the notification the first time. Haven't had time to work on stuff besides work too much. But will push this one

**Comment by AssisrMatheus** [comment]
The change is pushed but there's still an issue with the publishing process: https://github.com/AssisrMatheus/sidebar-markdown-notes/actions/runs/3054863344

Seems simple enough, I can fix it when I get the time, or if you want, you can open a quick pr that fixes it and I will gladly merge

**Pull request merged**
